name: "Setup common"
description: "Setup common"
runs:
  using: "composite"
  steps:
    - run: sudo apt-get update
      shell: bash

    - run: sudo apt-get install -y pkg-config build-essential libudev-dev
      shell: bash

    - uses: actions-rs/toolchain@v1
      name: Install minimal rust toolchain with clippy and rustfmt
      with:
        profile: minimal
        toolchain: ${{ env.RUST_TOOLCHAIN }}
        target: x86_64-unknown-linux-gnu
        components: rustfmt, clippy
        default: true

    - run: cargo install cargo-nextest --locked
      shell: bash

    - run: cargo nextest --version
      shell: bash
