name: "Base Setup"
description: "Checkout + Rust + (optionally) Solana+Anchor + Cargo cache"

# setting up anchor defaults to 'true'
inputs:
  include-anchor:
    description: "Whether to also setup Solana & Anchor"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
  - name: Checkout repo
    uses: actions/checkout@v3
    with:
      fetch-depth: 1

  - name: Setup common (Rust + clippy + rustfmt)
    uses: ./.github/actions/setup-common/

  - name: Cache Cargo registry & index
    uses: actions/cache@v3
    with:
      path: |
        ~/.cargo/registry/index
        ~/.cargo/registry/cache
        ~/.cargo/git/db
      key: cargo-registry-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}

  # only run Solana & Anchor setup if include-anchor == 'true'
  # unit tests and lint can skip this setup.
  - name: Setup Solana CLI
    if: ${{ inputs.include-anchor == 'true' }}
    uses: ./.github/actions/setup-solana-cli/

  - name: Setup Anchor CLI
    if: ${{ inputs.include-anchor == 'true' }}
    uses: ./.github/actions/setup-anchor-cli/

  - name: Cache Anchor build output
    if: ${{ inputs.include-anchor == 'true' }}
    uses: actions/cache@v3
    with:
      path: target/
      key: anchor-build-${{ runner.os }}-${{ env.ANCHOR_CLI_VERSION }}-${{ env.ANCHOR_SHA }}-${{ hashFiles('programs/**/Cargo.lock') }}
