#!/usr/bin/env bash
set -e

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
ROOT_DIR=$(realpath "${SCRIPT_DIR}/../../")

image_version=$1

[ -z "$image_version" ] && echo "Missing image_version argument" && exit 1

job_dir="$SCRIPT_DIR"
job_dir_rel=$(realpath --relative-to="$ROOT_DIR" "$job_dir")
job_name=$(basename "$job_dir_rel")

local_image_name="$job_name"
gcp_image_name="us-east1-docker.pkg.dev/marginfi-dev/main/dataflow/$local_image_name"

docker push "$gcp_image_name:$image_version"
