name: "Anchor Build"
description: "Anchor Build"
inputs:
  program_lib_name:
    description: "The program to build"
    required: true
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/setup-common/

    - uses: ./.github/actions/setup-anchor-cli/

    - uses: actions/cache@v2
      name: Cache Cargo registry + index
      id: cache-cargo-registry
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
        key: cargo-${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}

    - name: Cache Anchor Build
      uses: actions/cache@v2
      id: cache-anchor-build
      with:
        path: |
          ./target/
        key: build-${{ runner.os }}-${{env.ANCHOR_CLI_VERSION}}-${{env.ANCHOR_SHA}}-v0002-${{ hashFiles('./programs/**/**', '**/Cargo.lock') }}-${{ inputs.program_lib_name }}

    - run: ./scripts/build-program.sh ${{ inputs.program_lib_name }} mainnet
      if: steps.cache-anchor-build.outputs.cache-hit != 'true'
      shell: bash
