name: "Setup Solana CLI"
description: "Setup Solana CLI with caching"
runs:
  using: "composite"
  steps:
  # ─── Cache the Solana install ────────────────────────────────
  - name: Cache Solana CLI
    uses: actions/cache@v3
    id: cache-solana
    with:
      path: |
        ~/.local/share/solana/install
        ~/.cache/solana
      key: solana-cli-${{ runner.os }}-v${{ env.SOLANA_CLI_VERSION }}

  - name: Install Solana CLI
    if: steps.cache-solana.outputs.cache-hit != 'true'
    run: |
      sh -c "$(curl -sSfL https://release.anza.xyz/v${{ env.SOLANA_CLI_VERSION }}/install)"
    shell: bash

  - name: Add Solana to PATH
    run: |
      echo "${HOME}/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
    shell: bash

  # ─── Cache Solana keygen ────────────────────────────────
  - name: Cache solana-keygen binary
    uses: actions/cache@v3
    id: cache-keygen
    with:
      path: ~/.cargo/bin/solana-keygen
      key: solana-keygen-${{ runner.os }}-v${{ env.SOLANA_CLI_VERSION }}

  - name: Install solana-keygen
    if: steps.cache-keygen.outputs.cache-hit != 'true'
    run: |
      cargo install solana-keygen --version ${{ env.SOLANA_CLI_VERSION }} --locked
    shell: bash

  # ─── Always generate a key and set localnet───────────────
  - name: Generate keypair
    run: |
      solana-keygen new -s --no-bip39-passphrase --force
    shell: bash

  - name: Set Solana config
    run: |
      solana config set --url localhost
    shell: bash
