export enum LendingInstruction {
  InitLendingMarket = 0,
  SetLendingMarketOwnerAndConfig = 1,
  InitReserve = 2,
  RefreshReserve = 3,
  DepositReserveLiquidity = 4,
  RedeemReserveCollateral = 5,
  InitObligation = 6,
  RefreshObligation = 7,
  DepositObligationCollateral = 8,
  WithdrawObligationCollateral = 9,
  BorrowObligationLiquidity = 10,
  RepayObligationLiquidity = 11,
  LiquidateObligation = 12,
  FlashLoan = 13,
  DepositReserveLiquidityAndObligationCollateral = 14,
  WithdrawObligationCollateralAndRedeemReserveLiquidity = 15,
  UpdateReserveConfig = 16,
  LiquidateObligationAndRedeemReserveCollateral = 17,
  RedeemFees = 18,
  FlashBorrowReserveLiquidity = 19,
  FlashRepayReserveLiquidity = 20,
  ForgiveDebt = 21,
  UpdateMetadata = 22,
  SetObligationCloseabilityStatus = 23,
}

/** Instructions defined by the program */
export enum TokenInstruction {
  InitializeMint = 0,
  InitializeAccount = 1,
  InitializeMultisig = 2,
  Transfer = 3,
  Approve = 4,
  Revoke = 5,
  SetAuthority = 6,
  MintTo = 7,
  Burn = 8,
  CloseAccount = 9,
  FreezeAccount = 10,
  ThawAccount = 11,
  TransferChecked = 12,
  ApproveChecked = 13,
  MintToChecked = 14,
  BurnChecked = 15,
  InitializeAccount2 = 16,
  SyncNative = 17,
  InitializeAccount3 = 18,
  InitializeMultisig2 = 19,
  InitializeMint2 = 20,
}

export enum WrapperLendingInstruction {
  RepayMaxObligationLiquidityInstruction = 1,
  DepositMaxReserveLiquidityAndObligationCollateral = 2,
  WithdrawExact = 3,
}
