#!/usr/bin/env bash
set -e

script_dir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
root_dir=$(git rev-parse --show-toplevel)

image_tag=$1

echo "$root_dir"
echo "$script_dir"

[ -z "$image_tag" ] && echo "Missing image_tag argument" && exit 1

crate_dir_rel=$(realpath --relative-to="$root_dir" "$script_dir")

echo "$crate_dir_rel"

cd "$root_dir"

local_image_name="marginfi-v2-indexer"
gcp_image_name="us-east1-docker.pkg.dev/marginfi-dev/main/$local_image_name"

docker build -f "$crate_dir_rel/Dockerfile" --platform=linux/amd64 --tag "$gcp_image_name:$image_tag" .
