#!/usr/bin/env bash
set -e

image_tag=$1

[ -z "$image_tag" ] && echo "Missing image_tag argument" && exit 1

local_image_name="marginfi-v2-indexer"
gcp_image_name="us-east1-docker.pkg.dev/marginfi-dev/main/$local_image_name"

docker push "$gcp_image_name:$image_tag"
