#!/usr/bin/env bash
set -e

script_dir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

image_version=$1
region=$2

[ -z "$image_version" ] && echo "Missing image_version argument" && exit 1
[ -z "$region" ] && echo "Missing region argument" && exit 1

job_dir=$(realpath "$script_dir")
job_name=$(basename "$job_dir")

#gcloud dataflow flex-template run "$job_name" \
#    --template-file-gcs-location "gs://dataflow_jobs_marginfi_v2/templates/$job_name.json" \
#    --region "$region"  \
#    --parameters input_topic=projects/marginfi-dev/topics/marginfi-v2-devnet-transactions-raw,output_table_namespace=marginfi-dev:marginfi_v2_devnet.event,cluster=devnet,min_idl_version=4