#!/usr/bin/env bash
set -e

job_id=$1

[ -z "$job_id" ] && echo "Missing job_id argument" && exit 1

gcloud dataflow flex-template run "$job_id" \
  --template-file-gcs-location gs://dataflow_jobs_marginfi_v2/templates/marginfi-v2-event-parsing-stream.json \
  --region us-central1  \
  --parameters input_topic=projects/marginfi-dev/topics/marginfi-v2-mainnet-transactions-raw,output_table_namespace=marginfi-dev:marginfi_v2.event,cluster=mainnet \
  --update