#!/usr/bin/env bash
set -e

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
ROOT_DIR=$(realpath "${SCRIPT_DIR}/../")

job_dir=$1
image_version=$2

[ -z "$job_dir" ] && echo "Missing job_dir argument" && exit 1
[ -z "$image_version" ] && echo "Missing image_version argument" && exit 1


job_dir=$(realpath "$job_dir")
job_name=$(basename "$job_dir")
job_dir_rel=$(realpath --relative-to="$ROOT_DIR" "$job_dir")

cd "$ROOT_DIR"

local_image_name="$job_name"
gcp_image_name="us-east1-docker.pkg.dev/marginfi-dev/main/dataflow/$local_image_name"

docker build --platform=linux/amd64 --build-arg JOB_DIRECTORY="$job_dir_rel" --tag "$job_name" "$ROOT_DIR"
docker tag "$local_image_name" "$gcp_image_name:$image_version"
