#!/usr/bin/env bash
set -e

job_dir=$1
image_version=$2

[ -z "$job_dir" ] && echo "Missing job_dir argument" && exit 1
[ -z "$image_version" ] && echo "Missing image_version argument" && exit 1

job_dir=$(realpath "$job_dir")
job_name=$(basename "$job_dir")

local_image_name="$job_name"
gcp_image_name="us-east1-docker.pkg.dev/marginfi-dev/main/dataflow/$local_image_name"
gcp_template_gs_path="gs://dataflow_jobs_marginfi_v2/templates/$job_name.json"
metadata_local_path="$job_dir/metadata.json"

gcloud dataflow flex-template build \
    "$gcp_template_gs_path" \
    --image "$gcp_image_name:$image_version" \
    --sdk-language "PYTHON" \
    --metadata-file "$metadata_local_path"
