#!/usr/bin/env bash
set -e

job_dir=$1
image_version=$2

[ -z "$job_dir" ] && echo "Missing job_dir argument" && exit 1
[ -z "$image_version" ] && echo "Missing image_version argument" && exit 1

job_dir=$(realpath "$job_dir")
job_name=$(basename "$job_dir")

local_image_name="$job_name"
gcp_image_name="us-east1-docker.pkg.dev/marginfi-dev/main/dataflow/$local_image_name"

docker push "$gcp_image_name:$image_version"
