name: Deploy

on:
  workflow_run:
    workflows: ["Manual PR Workflow"]
    types:
      - manual

jobs:
  build-verifiable:
    name: Generate verifiable build
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        program:
          - marginfi
          # - liquidity_incentive_program

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build-verifiable-program/
        with:
          program: ${{ matrix.program }}
