name: Deploy

on:
  workflow_dispatch:
    inputs:
      program_lib_name:
        description: "Program library name"
        required: true
        type: choice
        options:
          - marginfi
          - liquidity_incentive_program
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

env:
  RUST_TOOLCHAIN: 1.71.0
  SOLANA_CLI_VERSION: 1.16.20
  ANCHOR_CLI_VERSION: 0.29.0
  ANCHOR_SHA: fc9fd6d24b9be84abb2f40e47ed3faf7b11864ae
  CARGO_TERM_COLOR: always
  CARGO_BUILD_TARGET: x86_64-unknown-linux-gnu

jobs:
  build-verifiable:
    name: Generate verifiable build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build-verifiable-program/
        with:
          program_lib_name: ${{ inputs.program_lib_name }}
